name: Line Notify on Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and test
        run: echo "Build and test steps here"

  run-if-success:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - name: Line Notify on Success
        uses: louis70109/line-notify-action@master
        with:
          token: ${{ secrets.LINE_NOTIFY_MYG }}
          message: |
            Triggered ${{github.repository}}#${{ github.ref_name }}
            [COMMIT] => ${{ github.event.head_commit.message }}
            [ACTOR] => ${{ github.actor }}
            [***SUCCESS***]
          sticker-id: 16581271
          sticker-package-id: 8522

  run-if-failed:
    runs-on: ubuntu-latest
    needs: build
    if: failure()
    steps:
      - name: Line Notify on Failure
        uses: louis70109/line-notify-action@master
        with:
          token: ${{ secrets.LINE_NOTIFY_MYG }}
          message: |
            Triggered ${{github.repository}}#${{ github.ref_name }}
            [COMMIT] => ${{ github.event.head_commit.message }}
            [ACTOR] => ${{ github.actor }}
            [***FAILED***]
          sticker-id: 16581283
          sticker-package-id: 8522
